name: cdintelligencemedia
favicon: null
layout_spectrum: 0.24306
typography_spectrum: 0.58072
title: 'CD Intelligence Media << enjoy the ride >>'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#262469'
    - '#e4e5e6'
    - '#95979a'
    - '#e41e25'
    - '#f8971d'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
