name: cdintelligencemedia
favicon: null
layout_spectrum: 0.24306
typography_spectrum: 0.8409
title: 'CD Intelligence Media << enjoy the ride >>'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#202020'
    - '#4d4d4d'
    - '#d3d3d3'
    - '#a4a4a4'
    - '#4edf00'
  brandStrength: 0.5
  lightness: 0.9977867319248617
  saturation: 0.10733501426875591
  rhythmicContrast: 0.75
purpose: []
